# Imagen base ligera con Node.js
FROM node:20-alpine


WORKDIR /app

RUN npm install tailwindcss @tailwindcss/cli
# RUN npm install daisyui
RUN npm i -D daisyui@latest
RUN mkdir css

ENTRYPOINT ["npx", "tailwindcss", "-i", "./css/input.css", "-o", "./css/output.css", "--watch"]